# Generated by Django 4.0.6 on 2022-07-17 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal', models.CharField(choices=[('BF', 'Breakfast'), ('L', 'Lunch'), ('D', 'Dinner')], default='L', max_length=50)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'MenuItem',
            },
        ),
        migrations.AlterModelTable(
            name='restaurant',
            table='Restaurant',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='menu',
            field=models.ForeignKey( on_delete=django.db.models.deletion.CASCADE, related_name='menu_item', to='menu.menu'),
            preserve_default=False,
        ),
    ]
