# Generated by Django 4.0.6 on 2022-07-17 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_fooditem_remove_menu_meal'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='food',
            field=models.ManyToManyField(to='menu.fooditem'),
        ),
    ]
