# Generated by Django 4.0.6 on 2022-07-17 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_menu_food'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='meal',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner')], default='Lunch', max_length=50),
        ),
    ]
