# Generated by Django 4.0.6 on 2022-07-17 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("menu", "0005_alter_fooditem_meal"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.TextField()),
                ("vote", models.SmallIntegerField(choices=[(1, "+1"), (-1, "-1")])),
                (
                    "time_stamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "votes",
                "unique_together": {("user", "content_type", "object_id")},
            },
        ),
        migrations.AddField(
            model_name="menu",
            name="votes",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="menu.vote"
            ),
            preserve_default=False,
        ),
    ]
